### ISSUE TITLE
JWT bug fix

### ISSUE THREAD

**Issue by NathanHTC** [NathanHTC/Authentication#2]
router.post("/reset-password/:id/:token", async (req, res) =>  has an JsonWebTokenError: invalid signature error
tried console.log to fix it, here is the output
token is eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZDhkOTc2OTRkOGRhNmU0ZWM0ZDMyNCIsImVtYWlsIjoiMDAwc2F2aW9yMDAxQGdtYWlsLmNvbSIsImlhdCI6MTcwODcxNjEyNCwiZXhwIjoxNzA4NzE3MDI0fQ.BuHTLxwsBxs8uxFc5lVUxpESJdVrbaN0tHZPoDgkWdY
user is: 000savior001@gmail.com

error message
JsonWebTokenError: invalid signature
    at /Users/solomon/Downloads/Github/Projects/Authentication/node_modules/jsonwebtoken/verify.js:133:19
    at getSecret (/Users/solomon/Downloads/Github/Projects/Authentication/node_modules/jsonwebtoken/verify.js:90:14)

**Comment by NathanHTC** [comment]
very last module to be fix, all other modules are tested and bug free

**Comment by NathanHTC** [comment]
problem solved
'reset password endpoint debugged | all end points tests pass, project
 complete'
